version: '3.8'
services:
  app:
    build: ./app/
    ports:
      - 5000:5000
    networks:
      - ntw
    volumes:
      - .:/usr/src/results
      - ./app/backups:/usr/src/backups
    depends_on:
      - db
      - flyway
      - redis
      #- mongodb
      
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_USER=dreamTeam
      - POSTGRES_PASSWORD=dreamTeam
      - POSTGRES_DB=zno_data
      - POSTGRES_HOST=db
    ports:
      - '5432:5432'
    networks:
      - ntw
      
  flyway:
    build: ./flyway/
    restart: always
    networks:
      - ntw
    depends_on:
      - db
      
  redis:
    image: redis:latest
    restart: always
    networks:
      - ntw
      
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=your_database_name
    ports:
      - '27017:27017'
    networks:
      - ntw
    #volumes:
    #  - ./mongodb.conf:/etc/mongod.conf
    #command: mongod --config /etc/mongod.conf
networks:
  ntw:



