CREATE TABLE IF NOT EXISTS tbl_zno_results(
    OUTID char(36) PRIMARY KEY,
    Birth int2 NOT NULL,
    SEXTYPENAME char(10) NOT NULL,
    REGNAME char(30) NOT NULL,
    AREANAME char(30) NOT NULL,
    TERNAME char(40) NOT NULL,
    REGTYPENAME varchar(120) NULL,
    TerTypeName char(5) NULL,
    ClassProfileNAME char(40) NULL,
    ClassLangName char(10) NULL,
    EONAME varchar(300) NULL,
    EOTYPENAME char(60) NULL,
    EORegName char(30) NULL,
    EOAreaName char(50) NULL,
    EOTerName char(40) NULL,
    EOParent varchar(300) NULL,
    UkrTest char(30) NULL,
    UkrTestStatus char(20) NULL,
    UkrBall100 char(5) NULL,
    UkrBall12 char(5) NULL,
    UkrBall char(5) NULL,
    UkrAdaptScale char(1) NULL,
    UkrPTName varchar(300) NULL,
    UkrPTRegName varchar(30) NULL,
    UkrPTAreaName char(50) NULL,
    UkrPTTerName char(40) NULL,
    histTest char(20) NULL,
    HistLang char(10) NULL,
    histTestStatus char(20) NULL,
    histBall100 char(5) NULL,
    histBall12 char(5) NULL,
    histBall char(5) NULL,
    histPTName varchar(300) NULL,
    histPTRegName char(30) NULL,
    histPTAreaName char(50) NULL,
    histPTTerName char(40) NULL,
    mathTest char(10) NULL,
    mathLang char(10) NULL,
    mathTestStatus char(20) NULL,
    mathBall100 char(5) NULL,
    mathBall12 char(5) NULL,
    mathBall char(5) NULL,
    mathPTName varchar(300) NULL,
    mathPTRegName char(30) NULL,
    mathPTAreaName char(50) NULL,
    mathPTTerName char(40) NULL,
    physTest char(10) NULL,
    physLang char(10) NULL,
    physTestStatus char(20) NULL,
    physBall100 char(5) NULL,
    physBall12 char(5) NULL,
    physBall char(5) NULL,
    physPTName varchar(300) NULL,
    physPTRegName char(30) NULL,
    physPTAreaName char(50) NULL,
    physPTTerName char(40) NULL,
    chemTest char(10) NULL,
    chemLang char(10) NULL,
    chemTestStatus char(20) NULL,
    chemBall100 char(5) NULL,
    chemBall12 char(5) NULL,
    chemBall char(5) NULL,
    chemPTName varchar(300) NULL,
    chemPTRegName char(30) NULL,
    chemPTAreaName char(50) NULL,
    chemPTTerName char(40) NULL,
    bioTest char(10) NULL,
    bioLang char(10) NULL,
    bioTestStatus char(20) NULL,
    bioBall100 char(5) NULL,
    bioBall12 char(5) NULL,
    bioBall char(5) NULL,
    bioPTName varchar(300) NULL,
    bioPTRegName char(30) NULL,
    bioPTAreaName char(50) NULL,
    bioPTTerName char(40) NULL,
    geoTest char(10) NULL,
    geoLang char(10) NULL,
    geoTestStatus char(20) NULL,
    geoBall100 char(5) NULL,
    geoBall12 char(5) NULL,
    geoBall char(5) NULL,
    geoPTName varchar(300) NULL,
    geoPTRegName char(30) NULL,
    geoPTAreaName char(50) NULL,
    geoPTTerName char(40) NULL,
    engTest char(20) NULL,
    engTestStatus char(20) NULL,
    engBall100 char(5) NULL,
    engBall12 char(5) NULL,
    engDPALevel char(30) NULL,
    engBall char(5) NULL,
    engPTName varchar(300) NULL,
    engPTRegName char(30) NULL,
    engPTAreaName char(50) NULL,
    engPTTerName char(40) NULL,
    fraTest char(20) NULL,
    fraTestStatus char(20) NULL,
    fraBall100 char(5) NULL,
    fraBall12 char(5) NULL,
    fraDPALevel char(30) NULL,
    fraBall char(5) NULL,
    fraPTName varchar(200) NULL,
    fraPTRegName char(30) NULL,
    fraPTAreaName char(50) NULL,
    fraPTTerName char(40) NULL,
    deuTest char(20) NULL,
    deuTestStatus char(20) NULL,
    deuBall100 char(5) NULL,
    deuBall12 char(5) NULL,
    deuDPALevel char(30) NULL,
    deuBall char(5) NULL,
    deuPTName varchar(200) NULL,
    deuPTRegName char(30) NULL,
    deuPTAreaName char(50) NULL,
    deuPTTerName char(40) NULL,
    spaTest char(20) NULL,
    spaTestStatus char(20) NULL,
    spaBall100 char(5) NULL,
    spaBall12 char(5) NULL,
    spaDPALevel char(30) NULL,
    spaBall char(5) NULL,
    spaPTName varchar(200) NULL,
    spaPTRegName char(30) NULL,
    spaPTAreaName char(50) NULL,
    spaPTTerName char(40) NULL
);

INSERT INTO tbl_zno_results (OUTID, Birth, SEXTYPENAME, REGNAME, AREANAME, TERNAME)
VALUES ('admin', 1, 'undef', 'undef', 'undef', 'undef')
ON CONFLICT (outid) DO NOTHING;


